backend:
  name: git-gateway
  repo: casperleerink/breathingbass
# media_folder: static/assets
public_folder: /assets
media_library:
  name: cloudinary
  config:
    cloud_name: "casperleerink"
    api_key: "173738255589443"
    folder:
      path: "breathingbass"
logo_url: "https://cdn.dribbble.com/users/610636/screenshots/6454161/sloth_2-01.png"
collections:
  - label: "Pages" 
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/pages/index.md"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "body", name: "body", widget: "markdown"}
      # - label: "About Page"
      #   name: "about"
      #   file: "src/pages/about.md"
      #   fields:
      #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
      #     - {label: "body", name: "body", widget: "markdown"}
  - label: "Performances"
    name: "performances"
    folder: "src/pages/performances"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "performance-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", default: "", dateFormat: "DD.MM.YYYY", timeFormat: "hh.mm.a"}
      - {label: "Main Image", name: "mainImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Biographies"
    name: "biographies"
    folder: "src/pages/biographies"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Main Image", name: "mainImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}